<?php
$currentPage = $_SERVER['REQUEST_URI'];
?>
<div style="font-size: 130%; background: cadetblue;">
    <ul style="list-style-type: none;">
        <li style="float: left; padding: 10px 20px;">
            <a href="/auth">Авторизация</a>
        </li>
        <li style="float: left; padding: 10px 20px;">
            <a href="/register">Регистрация</a>
        </li>
        <li style="float: left; padding: 10px 20px;">
            <a href="/users">Список пользователей</a>
        </li>
        <li style="padding: 10px 20px;">
            <a href="/files">Список файлов</a>
        </li>
    </ul>
</div>